---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./tests/qbittorrent/config:/config
      - ./tests/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  graphic-torrent:
    image: graphic-torrent:latest
    container_name: graphic-torrent
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - QB_URL=${QB_URL}
      - QB_USERNAME=${QB_USERNAME}
      - QB_PASSWORD=${QB_PASSWORD}
#      - FLASK_ENV=development
#      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    restart: no
